package gameServer;
public enum Command {
  CONNECTED, MOVE, HIT, DEAD, DISCONNECT,
  NEW_PLAYER, GET_ALL, UPDATE_ALL, REMOVE,
  RECEIVE_ALL, GET_SERVER_TIME, FIRE_LASER,
  FIRE_MISSILE, LASER_FIRED, MISSILE_FIRED
}
