package gameServer;
public enum Command {
	CONNECTED, MOVE, STOP, HIT, DEAD, DISCONNECT,
	NEW_PLAYER, UPDATE_ALL, REMOVE, RECEIVE_ALL,
	GET_SERVER_TIME, FIRE_LASER, FIRE_MISSILE,
	LASER_FIRED, MISSILE_FIRED, PING
}
